INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'colorjitter', 'normalize']

DATASET:
  NAME: 'TerraIncognitaDG'

MODEL:
  BACKBONE:
    NAME: 'resnet50_draac_v3'
    PRETRAINED: True
  INIT_WEIGHTS: 'checkpoints/resnet50_draac_v3_pretrained.pth'
